name:                my-palette
version:             0.1.0
synopsis:            My palette configuration
github:              dogonthehorizon/my-xmonad
license:             MIT
author:              Fernando Freire
maintainer:          Fernando Freire <dogonthehorizon@gmail.com>
copyright:           2020 Fernando Freire
category:            CLI

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
