resolver: lts-19.33
rebuild-ghc-options: true
packages:
  - my-xmonad
  - my-xmobar
  - my-palette
  - xmonad
  - xmonad-contrib
  - xmobar
extra-deps:
  - netlink-1.1.1.0@sha256:d83424b5ba9921191449e4b1f53c7cba7f4375f2c55a9b737c77e982e1f40d00,3689
  # Needed for tests
  - smallcheck-series-0.6.1.1
  - cairo-0.13.8.2@sha256:ef1709c3c4d2c6d68a9a51d9f220dccc0745f6468d2d0868c15a7ecdf8f325a1,4078
  - pango-0.13.8.2@sha256:d4057ebddade4cde3e25d7755b5e030e7a7e56fe7365afd37916a7bba46d3fd9,3917
  - glib-0.13.8.2@sha256:f44b829e741b3c3244d523f60b058701dfc067ff64c2ba61d43be4cccfc2663d,3156
flags:
  xmobar:
    with_inotify: true
    with_nl80211: true
    with_datezone: true
    with_mpris: true
    with_dbus: true
    with_xpm: true
    with_threaded: true
    with_rtsopts: true
    with_weather: true
    with_alsa: true
ghc-options:
  "$locals": -threaded -rtsopts -with-rtsopts="-N +RTS --nonmoving-gc -RTS" -O -optc-O3
## Color
# Solarized dark theme
stack-colors: error=31:good=32:shell=35:dir=34:recommendation=32:target=95:module=35:package-component=95:secondary=92:highlight=32
color: always
