name:                my-xmobar
version:             0.1.0
synopsis: My XMobar configuration
github: dogonthehorizon/my-xmonad
license:             MIT
author:              Fernando Freire
maintainer:          Fernando Freire <dogonthehorizon@gmail.com>
copyright:           2020 Fernando Freire
category:            CLI

dependencies:
  - base >= 4.7 && < 5
  - xmobar

library:
  source-dirs: src

executables:
  my-xmobar:
    source-dirs:      app
    main:             xmobar.hs
    dependencies:
      - my-xmobar
